# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple_record}
  s.version = "2.1.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Travis Reeder}, %q{Chad Arimura}, %q{RightScale}]
  s.date = %q{2011-07-04}
  s.description = %q{ActiveRecord like interface for Amazon SimpleDB. Store, query, shard, etc. By http://www.appoxy.com}
  s.email = %q{travis@appoxy.com}
  s.extra_rdoc_files = [
    "LICENSE.markdown",
    "README.markdown"
  ]
  s.files = [
    "lib/simple_record.rb",
    "lib/simple_record/active_sdb.rb",
    "lib/simple_record/attributes.rb",
    "lib/simple_record/callbacks.rb",
    "lib/simple_record/encryptor.rb",
    "lib/simple_record/errors.rb",
    "lib/simple_record/json.rb",
    "lib/simple_record/logging.rb",
    "lib/simple_record/password.rb",
    "lib/simple_record/results_array.rb",
    "lib/simple_record/sharding.rb",
    "lib/simple_record/stats.rb",
    "lib/simple_record/translations.rb",
    "lib/simple_record/validations.rb"
  ]
  s.homepage = %q{http://github.com/appoxy/simple_record/}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{ActiveRecord like interface for Amazon SimpleDB. By http://www.appoxy.com}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws>, [">= 0"])
      s.add_runtime_dependency(%q<concur>, [">= 0"])
    else
      s.add_dependency(%q<aws>, [">= 0"])
      s.add_dependency(%q<concur>, [">= 0"])
    end
  else
    s.add_dependency(%q<aws>, [">= 0"])
    s.add_dependency(%q<concur>, [">= 0"])
  end
end

